# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/kcontacts' : '@latest'
    'kde/pim/akonadi' : '@same'
    'kde/pim/kidentitymanagement' : '@same'
    'kde/pim/kmailtransport' : '@same'
    'kde/pim/libkdepim' : '@same'
    'kde/pim/mailcommon' : '@same'
    'kde/pim/mailimporter' : '@same'
    'kde/pim/messagelib' : '@same'
    'kde/pim/pimcommon' : '@same'
