# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcontacts': '@latest-kf6'
    'pim/akonadi': '@same'
    'pim/kidentitymanagement': '@same'
    'pim/kmailtransport': '@same'
    'pim/mailcommon': '@same'
    'pim/mailimporter': '@same'
    'pim/messagelib': '@same'
    'pim/pimcommon': '@same'
    'third-party/qtkeychain': '@latest-kf6'

Options:
 require-passing-tests-on: ['@all']
